### ISSUE TITLE
Feedback Christiaan

### ISSUE THREAD

**Issue by christiaanbraun** [MaylinnK/Functional-Programming#1]
Feedback voor Maylinn
Application of subject matter
1-2: Het project werkt, data is overzichtelijk.
3-4: Je transformeert de data door het van verschillende pagina’s te halen en samen te voegen in een nieuwe array. Dit is makkelijker dan beide api’s zelf aanroepen en opzoek gaan anar de data.
5-6: Je gebruikt verschillende functies voor verschillende doeleinde. De getBerryData functie zou misschien nog opgedeeld kunnen worden.
7-8: Chaining wordt gebruikt, over de side effect kan ik niet veel zeggen. Dus denk dat dat goed is

Quality
1-2: Je readme mist nog.
3-4: Duidelijk logboek, en je code is consistent 
5-6: Nog even aangeven wat je project is en wat het doet in de readme
7-8: 
9-10:
 
Process
1-2: Het is goed gedocumenteerd
3-4: ""
5-6: Mooi beschreven waarom je de API gekozen hebt die je hebt. Via de code snippets kan ik goed zien wat je proces is.

**Comment by MaylinnK** [comment]
Feedback verwerkt
